# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/primou/unzip-files.sh - DO NOT EDIT

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/htc/primou/proprietary/libaudioalsa.so:obj/lib/libaudioalsa.so \
    vendor/htc/primou/proprietary/libcamera.so:obj/lib/libcamera.so \
    vendor/htc/primou/proprietary/libv8.so:obj/lib/libv8.so

# All the blobs necessary for primou
PRODUCT_COPY_FILES += \
    vendor/htc/primou/proprietary/akmd:/system/bin/akmd \
    vendor/htc/primou/proprietary/awb_camera:/system/bin/awb_camera \
    vendor/htc/primou/proprietary/bma150_usr:/system/bin/bma150_usr \
    vendor/htc/primou/proprietary/logcat2:/system/bin/logcat2 \
    vendor/htc/primou/proprietary/lsc_camera:/system/bin/lsc_camera \s
    vendor/htc/primou/proprietary/rmt_storage:/system/bin/rmt_storage \
    vendor/htc/primou/proprietary/BCM4330B1_002.001.003.0634.0690.hcd:system/etc/firmware/BCM4330B1_002.001.003.0634.0690.hcd \
    vendor/htc/primou/proprietary/default.acdb:system/etc/firmware/default.acdb \
    vendor/htc/primou/proprietary/default_org.acdb:system/etc/firmware/default_org.acdb \
    vendor/htc/primou/proprietary/default_org_wb.acdb:system/etc/firmware/default_org_wb.acdb \
    vendor/htc/primou/proprietary/vidc_720p_command_control.fw:system/etc/firmware/vidc_720p_command_control.fw \
    vendor/htc/primou/proprietary/vidc_720p_h263_dec_mc.fw:system/etc/firmware/vidc_720p_h263_dec_mc.fw \
    vendor/htc/primou/proprietary/vidc_720p_h264_dec_mc.fw:system/etc/firmware/vidc_720p_h264_dec_mc.fw \
    vendor/htc/primou/proprietary/vidc_720p_h264_enc_mc.fw:system/etc/firmware/vidc_720p_h264_enc_mc.fw \
    vendor/htc/primou/proprietary/vidc_720p_mp2_dec_mc.fw:system/etc/firmware/vidc_720p_mp2_dec_mc.fw \
    vendor/htc/primou/proprietary/vidc_720p_mp4_dec_mc.fw:system/etc/firmware/vidc_720p_mp4_dec_mc.fw \
    vendor/htc/primou/proprietary/vidc_720p_mp4_enc_mc.fw:system/etc/firmware/vidc_720p_mp4_enc_mc.fw \
    vendor/htc/primou/proprietary/vidc_720p_vc1_dec_mc.fw:system/etc/firmware/vidc_720p_vc1_dec_mc.fw \
    vendor/htc/primou/proprietary/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    vendor/htc/primou/proprietary/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    vendor/htc/primou/proprietary/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/htc/primou/proprietary/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \
    vendor/htc/primou/proprietary/eglsubAndroid.so:/system/lib/egl/eglsubAndroid.so \
    vendor/htc/primou/proprietary/libEGL_adreno200.so:/system/lib/egl/libEGL_adreno200.so \
    vendor/htc/primou/proprietary/libGLESv1_CM_adreno200.so:/system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/htc/primou/proprietary/libGLESv2_adreno200.so:/system/lib/egl/libGLESv2_adreno200.so \
    vendor/htc/primou/proprietary/libq3dtools_adreno200.so:/system/lib/egl/libq3dtools_adreno200.so \
    vendor/htc/primou/proprietary/libaudioalsa.so:/system/lib/libaudioalsa.so \
    vendor/htc/primou/proprietary/libC2D2.so:/system/lib/libC2D2.so \
    vendor/htc/primou/proprietary/libcamera.so:/system/lib/libcamera.so \
    vendor/htc/primou/proprietary/libgemini.so:/system/lib/libgemini.so \
    vendor/htc/primou/proprietary/libgsl.so:/system/lib/libgsl.so \
    vendor/htc/primou/proprietary/libhtc_acoustic.so:/system/lib/libhtc_acoustic.so \
    vendor/htc/primou/proprietary/libhtc_ril.so:/system/lib/libhtc_ril.so \
    vendor/htc/primou/proprietary/libmmipl.so:/system/lib/libmmipl.so \
    vendor/htc/primou/proprietary/libmmjpeg.so:/system/lib/libmmjpeg.so \
    vendor/htc/primou/proprietary/liboemcamera.so:/system/lib/liboemcamera.so \
    vendor/htc/primou/proprietary/libOpenVG.so:/system/lib/libOpenVG.so \
    vendor/htc/primou/proprietary/libposteffect.so:/system/lib/libposteffect.so \
    vendor/htc/primou/proprietary/libsc-a2xx.so:/system/lib/libsc-a2xx.so \
    vendor/htc/primou/proprietary/libv8.so:system/lib/libv8.so
